const components = {
  "App": "AppComponents",
  "DeckEdit": "AppComponents",
  "HomePage": "AppComponents",
  "Playground": "AppComponents",
  "Button": "Visual",
  "Card": "Visual",
  "CardEditor": "Visual",
  "CardList": "Visual",
  "Checkbox": "Visual",
  "CodeVisualizer": "Visual",
  "Deck": "Visual",
  "Details": "Visual",
  "Dialog": "Visual",
  "DropDown": "Visual",
  "Grid": "Visual",
  "Icon": "Visual",
  "Input": "Visual",
  "Layout": "Visual",
  "Loading": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "RadioButton": "Visual",
  "RadioGroup": "Visual",
  "Route": "Visual",
  "Select": "Visual",
  "StarRating": "Visual",
  "Switch": "Visual",
  "TreeItem": "Visual",
  "TreeView": "Visual",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "Link": "Service",
  "LocalStorageManager": "Service",
  "Translator": "Service"
};

export default components;
